// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net7.WebApi.Test.Data;

#nullable disable

namespace Net7.WebApi.Test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Net7.WebApi.Test.Data.Entities.TeapotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teapots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1.7,
                            Description = "Some good teapot",
                            ImgUrl = "image1.png",
                            ManufacturerCountry = "Germany",
                            Price = 490.0,
                            Quantity = 6,
                            Title = "Teapot 1",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1.8,
                            Description = "Some good teapot",
                            ImgUrl = "image2.png",
                            ManufacturerCountry = "China",
                            Price = 515.0,
                            Quantity = 10,
                            Title = "Teapot 2",
                            WarrantyInMonths = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
